In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-2.3.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (91 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.3.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/santhosh/.local/share/pipx/venvs/notebook/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /home/santhosh/.local/share/pipx/venvs/notebook/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 5.6 MB/s eta 0:00:00[31m5.9 MB/s eta 0:00:01
Downloading numpy-2.3.0-cp312-cp312-manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 5.2 MB/s eta 0:00:00m eta 0:00:010:01:01
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.3.0 pandas-2.3.0 pytz-2025.2 tzdata-2025.2

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install fastparquet

Collecting fastparquet
  Downloading fastparquet-2024.11.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: pandas>=1.5.0 in /home/santhosh/.local/share/pipx/venvs/notebook/lib/python3.12/site-packages (from fastparquet) (2.3.0)
Requirement already satisfied: numpy in /home/santhosh/.local/share/pipx/venvs/notebook/lib/python3.12/site-packages (from fastparquet) (2.3.0)
Collecting cramjam>=2.3 (from fastparquet)
  Downloading cramjam-2.10.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.0 kB)
Collecting fsspec (from fastparquet)
  Downloading fsspec-2025.5.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: packaging in /home/santhosh/.local/share/pipx/venvs/notebook/lib/python3.12/site-packages (from fastparquet) (24.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/santhosh/.local/share/pipx/venvs/notebook/lib/python3.12/site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/santhosh/.local/share/pipx/venvs/notebook/lib/python3.12/site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/santhosh/.local/share/pipx/venvs/notebook/lib/python3.12/site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: six>=1.5 in /home/santhosh/.local/share/pipx/venvs/notebook/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Downloading fastparquet-2024.11.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 716.7 kB/s eta 0:00:00 kB/s eta 0:00:01:02
Downloading cramjam-2.10.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 965.6 kB/s eta 0:00:00B/s eta 0:00:01:01
Downloading fsspec-2025.5.1-py3-none-any.whl (199 kB)
Installing collected packages: fsspec, cramjam, fastparquet
Successfully installed cramjam-2.10.0 fastparquet-2024.11.0 fsspec-2025.5.1

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd
df=pd.read_parquet("yellow_tripdata_2018-01.parquet")
df.to_csv("yellow_jan2018.csv",index=False)

In [6]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2018-01-01 00:21:05,2018-01-01 00:24:23,1,0.5,1,N,41,24,2,4.5,0.5,0.5,0.00,0.0,0.3,5.80,NaN,NaN
1,1,2018-01-01 00:44:55,2018-01-01 01:03:05,1,2.7,1,N,239,140,2,14.0,0.5,0.5,0.00,0.0,0.3,15.30,NaN,NaN
2,1,2018-01-01 00:08:26,2018-01-01 00:14:21,2,0.8,1,N,262,141,1,6.0,0.5,0.5,1.00,0.0,0.3,8.30,NaN,NaN
3,1,2018-01-01 00:20:22,2018-01-01 00:52:51,1,10.2,1,N,140,257,2,33.5,0.5,0.5,0.00,0.0,0.3,34.80,NaN,NaN
4,1,2018-01-01 00:09:18,2018-01-01 00:27:06,2,2.5,1,N,246,239,1,12.5,0.5,0.5,2.75,0.0,0.3,16.55,NaN,NaN